all:
  children:
    RC_NETWORK:
      children:
          DC01:
            hosts:
              spine1:
                ansible_host: 10.255.1.32
              spine2:
                ansible_host: 10.255.1.33
              spine3:
                ansible_host: 10.255.1.34
              spine4:
                ansible_host: 10.255.1.35
              leaf1a:
                ansible_host: 10.255.1.36
              leaf1b:
                ansible_host: 10.255.1.37
              leaf2a:
                ansible_host: 10.255.1.38
              leaf2b:
                ansible_host: 10.255.1.39
              leaf3a:
                ansible_host: 10.255.1.40
              leaf3b:
                ansible_host: 10.255.1.41
              leaf4a:
                ansible_host: 10.255.1.42
              leaf4b:
                ansible_host: 10.255.1.43
          DC02:
            hosts:
              spine1:
                ansible_host: 10.233.1.32
              spine2:
                ansible_host: 10.233.1.33
              spine3:
                ansible_host: 10.233.1.34
              spine4:
                ansible_host: 10.233.1.35
              leaf1a:
                ansible_host: 10.233.1.36
              leaf1b:
                ansible_host: 10.233.1.37
              leaf2a:
                ansible_host: 10.233.1.38
              leaf2b:
                ansible_host: 10.233.1.39
              leaf3a:
                ansible_host: 10.233.1.40
              leaf3b:
                ansible_host: 10.233.1.41
              leaf4a:
                ansible_host: 10.233.1.42
              leaf4b:
                ansible_host: 10.233.1.43
